build:
	gcc disk.c -Wall -o disk
	gcc merge.c -Wall -o merge
	gcc envious_friend.c -Wall -o envious_friend

clean:
	rm -rv disk
	rm -rv merge
	rm -rv envious_friend

run_disk:
	./disk

run_merge:
	./merge

run_ef:
	./envious_friend

compile:
	chmod +x angry_parent.sh
	chmod +x disk.sh
	chmod +x envious_friend.sh
	chmod +x q4/speed.sh


run_ap:
	./angry_parent.sh

run_diskbash:
	./disk.sh

run_efbash:
	./envious_friend.sh

run_speed:
	./speed.sh